website/docs/user_guides/rust/rigid_body_simulation.mdx
- recommanded → recommended
- update [.dt field](https://docs.rs/rapier2d/0.5.0/rapier2d/dynamics/struct.IntegrationParameters.html#method.set_dt) access/set instructions.
- is → its
=> fix typos and outdated instructions

website/docs/user_guides/rust/rigid_body_simulation.mdx
- `ColliderShape` → [`SharedShape`](https://docs.rs/rapier2d/0.5.0/rapier2d/geometry/struct.SharedShape.html)
- `f32::PI` → `core::f32::consts::PI`
- `body_set` → `collider_set`, when referring to the colliders
- remove unused `Ball` import.
=> more fixes

website/docs/user_guides/templates/getting_started_js.mdx
The example code for Rapier2D in the JS section cannot work.
This line:
```js
console.log("Rigid-body position: ", position.x, position.y, position.z);
```
Has to be changed to:
```js
console.log("Rigid-body position: ", position.x, position.y);
```
Because `position.z` does not exist in the 2D coordinates system.
=> Fix error in the Javascript 2D example

docs/user_guides/templates/scene_queries_intersection_test.mdx, docs/user_guides/templates/scene_queries_ray_casting.mdx, docs/user_guides/templates/scene_queries_shape_casting.mdx
Fix Bevy code samples in scene queries chapter using undefined `query_pipeline` variable instead of `rapier_context`.
Looks like a copy-pasta error to me. Methods from `rapier_context.query_pipeline` use different parameters than ones used in samples so I guessed that methods from `rapier_context` were intended.
=> Fix Bevy code samples in scene queries chapter

docs/user_guides/templates/getting_started_bevy.mdx
- update the documentation of bevy_rapier to use bevy v0.8 methods according to [migaration guides on camera](https://bevyengine.org/learn/book/migration-guides/0.7-0.8/#camera-driven-rendering).
=> Update bevy_rapier documentation

docs/user_guides/templates/scene_queries_ray_casting.mdx, docs/user_guides/templates/scene_queries_shape_casting.mdx
These incorrectly reference the name for standalone rapier in the bevy 2d examples.
=> Fix Typos for bevy 2d examples in Scene Queries docs

docs/user_guides/templates/collider_type.mdx
This fixes a small typo when creating a `Sensor` (it's a [unit struct](https://docs.rs/bevy_rapier2d/latest/bevy_rapier2d/geometry/struct.Sensor.html)).
As always, thanks a lot for this work!
=> Fix invalid creation of Sensor type

docs/user_guides/templates/collider_creation_and_insertion.mdx, docs/user_guides/templates/joints.mdx
Fixes a couple examples in documentation using outdated `.insert(Sensor(true))` and `PrismaticJointBuilder::limit_axis` syntax.
=> update joint limits and sensor examples

docs/user_guides/templates/character_controller_setup.mdx, docs/user_guides/templates/colliders.mdx
Excellent documentation. It was very readable for someone who hasn't worked with physic engine before.
Here's a few minor typo/grammar fixes.
=> fix: typos and missing words in convex meshes doc

docs/user_guides/templates/scene_queries.mdx
Fix the link from scene_queries page to the Query Pipeline subsection of the simulation_structures page
=> Fix: broken QueryPipeline link

docs/user_guides/templates/advanced_collision_detection.mdx
The .iter() function is deprecated and replaced by .read()
=> Updated deprecated function in example

docs/user_guides/templates/joints.mdx
Add missing close parenthesis in joints rust examples
=> Add missing close parenthesis in joints rust examples

docs/user_guides/templates/advanced_collision_detection.mdx
Fix Physics Hooks chapter examples for Bevy engine and update the description. Examples now compiles successfully against bevy 0.11 and bevy_rapier 0.22.
Usages of deprecated Bevy API were also updated.
=> Fix Physics Hooks chapter for Bevy

docs/user_guides/templates/rigid_body_position.mdx
There's a duplicate code section here.
=> Fix rigid_body_position.mdx typo

docs/user_guides/templates/simulation_structures.mdx
This was removed in version 0.12.0
https://github.com/dimforge/rapier/blob/89e3d7650c84f96893376a79cbc120aeaeb74785/CHANGELOG.md?plain=1#L191
=> Delete mention of removed `PhysicsPipeline::step_generic`

docs/user_guides/templates/collider_type.mdx
Based on https://github.com/dimforge/rapier/issues/545, this is a likely point of confusion for users. Putting it in the documentation makes it clear it's intentional.
=> Update collider_type.mdx to clarify sensor collider mass

docs/user_guides/templates/scene_queries_ray_casting.mdx
The docs have code examples where `None` is given as a filter instead of a `QueryFilter` and there are extra closing delimiters. This doesn't compile.
Fix the docs.
=> Fix query filter and closing delimiters in Bevy ray casting docs

docs/user_guides/templates/collider_creation_and_insertion.mdx
Changed line:
Attach the `Collider` to an entity that is a *children* of the entity containing the RigidBody.
to:
Attach the `Collider` to an entity that is a *child* of the entity containing the RigidBody.
=> Fixed grammatical mistake in collider_creation_and_insertion.mdx

.github/workflows/links.yml, docs/user_guides/templates/joints.mdx
There's still https://codepen.io/sebcrozet/pen/poRQoKK which should be fixed.
- relevant: https://github.com/dimforge/rapier.rs/pull/47
=> Fix a link + add a link checker action

README.md, community/support.mdx, package.json, yarn.lock
- improves https://github.com/dimforge/rapier.rs/issues/41
before this PR, it's easy to find ourselves in a situation where broken links appear a lot, a simple refresh adds a trailing slash, resulting in broken behaviour.
With docusaurus 3.5 ; trailing slashes don´t appear as much, resulting in a better experience.
The underlying issue still exist though, but is difficult to track.
=> update docusaurus to 3.5

docs/user_guides/templates/character_controller_snap_to_ground.mdx
I'm writing a game that makes use of rapier, and I was scratching my head for quite a while trying to figure out why snap to ground wasn't working. Turned out to be because of [this line of code](https://github.com/dimforge/rapier/blob/3855592447b01ee80240f882c8edc140b2d8e18d/src/control/character_controller.rs#L402). Whereas the docs say that snapping to ground requires no up component, the implementation actually requires it to be less than `-1e-5`. I had been setting it to 0 when grounded, thus the confusion.
=> Update snap to ground documentation to match implementation
